image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      sudo apt-get update -y && sudo apt-get upgrade -y
      sudo apt-get install nginx -y
      sudo service nginx start
    command: |
      echo "Environment set up!"

ports:
  - port: 80
    onOpen: open-preview
    
